apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend-v1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: frontend
        api: external
        version: v1.0.0     
    spec:
      containers:
      - image: selmy/udacity-frontend
        name: frontend
        imagePullPolicy: Always          
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always

