apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
  - name: http
    port: 8100
    targetPort: http
  selector:
    app: frontend
    version: v1.0.0
---  
