apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontendinfo
spec:
  hosts:
  - "*"
  gateways:
  - frontend-gateway
  http:
    - route:
      - destination:
          host: frontend
          port:
            number: 8100
        weight: 0
      - destination:
          host: frontend-v2
          port:
            number: 8100
        weight: 100