apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
        app: frontend
        version: v1.0.0
  template:
    metadata:
      labels:
        app: frontend
        version: v1.0.0     
    spec:
      containers:
      - image: selmy/udacity-frontend:v2
        name: frontend
        imagePullPolicy: IfNotPresent        
        ports:
        - name: http
          containerPort: 80
