apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend-v2
spec:
  ports:
  - name: http
    port: 8100
    targetPort: http
  selector:
    service: frontend
    version: v2.0.0
#  type: LoadBalancer    
